### ISSUE TITLE
请问一下具体是怎么操作呢，我替换了之后就启动不了UNRAID了

### ISSUE THREAD

**Issue by SuperBambooo** [fanhuanji/rtl8125-for-unraid-6.8.2#5]
我是先把unraid关机以后，下载bzmodules与bzmodules.sha256，放到U盘里替换了原来的文件，然后插回机器开机进不去unraid系统。并且把备份文件放回去以后也是进不去系统，不知道我问题出在哪里
我板U是i510400T(ES)+MSI B460M BOMBER
需求就是想用jellyfin调用核显来硬解
请大佬解答一下吧

**Comment by fanhuanji** [comment]
你确定是682版本的吗，有没有曾搞过其他的一些替换操作，再检查一下系统内核版本是4.19.98吗？

**Comment by fanhuanji** [comment]
备份文件放回去后不会进不去原来系统的，，备份的文件要是不行的话，那几个bz开头的跟后缀sha256的文件可以从你原来的安装包里面找，那些文件除非你手工替换(或者某些插件给替换)，不然是一直保持不变的，也就可以从安装包里找回原版，

**Comment by SuperBambooo** [comment]
可以这样吗？ 我制作U盘的时候直接把你这里2个文件放进去，然后设置U盘启动。

**Comment by fanhuanji** [comment]
> 可以这样吗？ 我制作U盘的时候直接把你这里2个文件放进去，然后设置U盘启动。

可以的，不过你得确定用的是同样版本的内核，起码不少群友用官方给的内核是能用的，，

如果还是不行，你留意下启动后的界面，里面有没有什么错误信息，然后命令行登录上看一下dmesg命令的输出里有没有什么红色的error信息输出，，

**Comment by SuperBambooo** [comment]
我的CPU是10400T的ES版，现在重做了U盘可以进系统了，但还是识别不了核显，不知道问题是不是出在CPU上面
大佬可否给个群号我进去学习学习
[url=https://sm.ms/image/reu8c7Ql5KdTjbH][img]https://i.loli.net/2021/03/04/reu8c7Ql5KdTjbH.png[/img][/url]
<a href="https://sm.ms/image/reu8c7Ql5KdTjbH" target="_blank"><img src="https://i.loli.net/2021/03/04/reu8c7Ql5KdTjbH.png" ></a>

**Comment by SuperBambooo** [comment]
对了 内核看过了 是4.19.98
Linux Tower 4.19.98-Unraid #1 SMP Sun Jan 26 09:15:03 PST 2020 x86_64 Genuine Intel(R) CPU 0000 @ 2.00GHz GenuineIntel GNU/Linux

**Comment by SuperBambooo** [comment]
对了 调用核显需要什么命令不？

**Comment by SuperBambooo** [comment]
好像可以了 搞成了
<a href="https://sm.ms/image/m5HNkwfVrYcAt7L" target="_blank"><img src="https://i.loli.net/2021/03/04/m5HNkwfVrYcAt7L.png" ></a>

**Comment by fanhuanji** [comment]
> 好像可以了 搞成了
> [![](https://camo.githubusercontent.com/28028390d43d55cb43e80c5bee7f2730409aa98a0831aaab73782b83a0db4270/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30332f30342f6d35484e6b7766567259634174374c2e706e67)](https://sm.ms/image/m5HNkwfVrYcAt7L)

unraid不是有个go启动脚本嘛，感觉你把modprobe语句丢进去自启就好了，，
