### ISSUE TITLE
强烈恳请大佬出一篇如何自己打包unraid网卡驱动的教程

### ISSUE THREAD

**Issue by trombonist852** [fanhuanji/rtl8125-for-unraid-6.8.2#7]
如题 望大佬不吝赐教 感激不尽！

**Comment by fanhuanji** [comment]
https://github.com/fanhuanji/rtl8125-driver-for-unraid-6.8.2/blob/main/compile_drivers.md

**Comment by trombonist852** [comment]
> https://github.com/fanhuanji/rtl8125-driver-for-unraid-6.8.2/blob/main/compile_drivers.md

感谢大神！我去学习去

**Comment by fanhuanji** [comment]
> > https://github.com/fanhuanji/rtl8125-driver-for-unraid-6.8.2/blob/main/compile_drivers.md
> 
> 感谢大神！我去学习去

客气了，共同学习，，

**Comment by trombonist852** [comment]
> > > https://github.com/fanhuanji/rtl8125-driver-for-unraid-6.8.2/blob/main/compile_drivers.md
> > 
> > 
> > 感谢大神！我去学习去
> 
> 客气了，共同学习，，

主要是我这个6.9.2的unraid ，2.5g的螃蟹卡只识别出1千兆的速度 自带驱动不能满速 尴尬。。。

**Comment by trombonist852** [comment]
按教程编译成功，也成功进入了unraid，但是网口速率还是1000m，虽然显示的是2.5g🤣不知道问题出在哪儿了…

**Comment by fanhuanji** [comment]
> 按教程编译成功，也成功进入了unraid，但是网口速率还是1000m，虽然显示的是2.5g🤣不知道问题出在哪儿了…

对端什么设备啊，另外你是下了最新的网卡驱动？

**Comment by trombonist852** [comment]
> > 按教程编译成功，也成功进入了unraid，但是网口速率还是1000m，虽然显示的是2.5g🤣不知道问题出在哪儿了…
> 
> 对端什么设备啊，另外你是下了最新的网卡驱动？

台式机 也是板载2.5g的网口，对的  是最瑞昱最新的网卡驱动编译的，地址是这个https://www.realtek.com/zh-tw/directly-download?downloadid=58dd86f5a9764df5032a45db6840cf05 万由的nas刷op的话smb共享传输可以达到200兆，但是用unraid就只能是100兆左右的速度了。。。

**Comment by fanhuanji** [comment]
> > > 按教程编译成功，也成功进入了unraid，但是网口速率还是1000m，虽然显示的是2.5g🤣不知道问题出在哪儿了…
> > 
> > 
> > 对端什么设备啊，另外你是下了最新的网卡驱动？
> 
> 台式机 也是板载2.5g的网口，对的 是最瑞昱最新的网卡驱动编译的，地址是这个https://www.realtek.com/zh-tw/directly-download?downloadid=58dd86f5a9764df5032a45db6840cf05 万由的nas刷op的话smb共享传输可以达到200兆，但是用unraid就只能是100兆左右的速度了。。。

你用iperf3跑下测试看看，两端都显示协商到2.5G的链路了是吗？跑下测试看看是不是问题不在网卡这里，，

**Comment by trombonist852** [comment]
> > > > 按教程编译成功，也成功进入了unraid，但是网口速率还是1000m，虽然显示的是2.5g🤣不知道问题出在哪儿了…
> > > 
> > > 
> > > 对端什么设备啊，另外你是下了最新的网卡驱动？
> > 
> > 
> > 台式机 也是板载2.5g的网口，对的 是最瑞昱最新的网卡驱动编译的，地址是这个https://www.realtek.com/zh-tw/directly-download?downloadid=58dd86f5a9764df5032a45db6840cf05 万由的nas刷op的话smb共享传输可以达到200兆，但是用unraid就只能是100兆左右的速度了。。。
> 
> 你用iperf3跑下测试看看，两端都显示协商到2.5G的链路了是吗？跑下测试看看是不是问题不在网卡这里，，

好，等我忙完跑跑看，对的，两端都是显示2.5g的速率了

**Comment by trombonist852** [comment]
> > > > 按教程编译成功，也成功进入了unraid，但是网口速率还是1000m，虽然显示的是2.5g🤣不知道问题出在哪儿了…
> > > 
> > > 
> > > 对端什么设备啊，另外你是下了最新的网卡驱动？
> > 
> > 
> > 台式机 也是板载2.5g的网口，对的 是最瑞昱最新的网卡驱动编译的，地址是这个https://www.realtek.com/zh-tw/directly-download?downloadid=58dd86f5a9764df5032a45db6840cf05 万由的nas刷op的话smb共享传输可以达到200兆，但是用unraid就只能是100兆左右的速度了。。。
> 
> 你用iperf3跑下测试看看，两端都显示协商到2.5G的链路了是吗？跑下测试看看是不是问题不在网卡这里，，

大神 我刚测过了  iperf以unraid为服务端，电脑为客户端的时候测速可以达到2.5g的速度 ，但是反过来以unraid为客户端，电脑为服务端速度只有1.6g左右
![image](https://user-images.githubusercontent.com/13253090/134792517-1879706e-592f-4e37-93c2-db9a93142620.png)
![image](https://user-images.githubusercontent.com/13253090/134792531-f50757e6-000e-43a0-9ada-5cab1e749a50.png)

**Comment by fanhuanji** [comment]
看起来很可以啊，网卡驱动工作应该是正常的，至于为什么unraid上跑测试只有1.6gb，我猜测是不是因为网卡bond之类设置的问题，导致影响了部分性能，另外，你是走的TCP测的吗，然后两边的包大小之类参数也是一样的吗？换换UDP统一下两边的参数测下再看看是不是有区别，，

至于为什么说共享文件访问只有千兆的速度，我怀疑是不是samba的问题，可能瓶颈出在samba或者磁盘上，，
